--Create the PEOPLE table
CREATE TABLE PEOPLE ( ID NUMBER PRIMARY KEY, FIRST_NAME VARCHAR2(256), LAST_NAME VARCHAR2(256), EMAIL VARCHAR2(128) );

--Insert initial data into the PEOPLE table
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (1, 'GEORGE', 'CLOONEY', 'gc@nomail.com');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES ((SELECT MAX(ID)+1 FROM PEOPLE), 'TOM', 'HARDY', 'th@nomail.com');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES ((SELECT MAX(ID)+1 FROM PEOPLE), 'MATT', 'DAMON', 'md@nomail.com');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES ((SELECT MAX(ID)+1 FROM PEOPLE), 'PETER', 'DINKLAGE', 'pd@nomail.com');
COMMIT;
