CREATE TABLE PERSON ( SSN NUMBER PRIMARY KEY, FIRST_NAME VARCHAR2(128), LAST_NAME VARCHAR2(128), EMAIL VARCHAR2(128), DEPT_CODE VARCHAR2(5));

ALTER TABLE PERSON ADD CONSTRAINT PERSON_DEPT_FK FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT(DEPT_CODE);

CREATE TABLE DEPARTMENT ( DEPT_CODE VARCHAR2(5) PRIMARY KEY, DEPT_NAME VARCHAR2(128), COMP_CODE VARCHAR2(10));

ALTER TABLE DEPARTMENT ADD CONSTRAINT DEPT_COMP_FK FOREIGN KEY (COMP_CODE) REFERENCES COMPANY(COMP_CODE);

CREATE TABLE COMPANY ( COMP_CODE VARCHAR2(10) PRIMARY KEY, COMP_NAME VARCHAR2(128), COMP_TYPE VARCHAR2(128), COUNTRY_CODE VARCHAR2(5));

ALTER TABLE COMPANY ADD CONSTRAINT COMP_COUNTRY_FK FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY(COUNTRY_CODE);

CREATE TABLE COUNTRY ( COUNTRY_CODE VARCHAR2(5) PRIMARY KEY, NAME VARCHAR2(128), RATING VARCHAR2(2));


INSERT INTO PERSON (SSN, FIRST_NAME, LAST_NAME, EMAIL, DEPT_CODE) VALUES (123456, 'GEORGE', 'CLOONEY', 'gc@nomail.com', 'ACT');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, COMP_CODE) VALUES ('ACT', 'Acting', 'HLWD');

INSERT INTO COMPANY (COMP_CODE, COMP_NAME, COMP_TYPE, COUNTRY_CODE) VALUES ('HLWD', 'Hollywood', 'Entertainment', 'US');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME, RATING) VALUES ('US', 'United States of America', '5');

COMMIT;
